### ISSUE TITLE
Complex comparison in ode_determine_initdt

### ISSUE THREAD

**Issue by jebej** [JuliaDiffEq/OrdinaryDiffEq.jl#45] opened 2017-05-05 15:17 UTC
It seems some changes were made which now has `ode_determine_initdt` compare complex numbers on line 10:
```julia
...
if d₀ < T0(1//10^(5)) || d₁ < T1(1//10^(5))
...
```

I can't figure out what T0 and T1 are however.

**Comment by jebej** [comment] 2017-05-05 15:18
Note: that's in my case, with complex initial variables (I assume that's the source of the issue), but the time interval itself is given with real numbers

**Comment by ChrisRackauckas** [comment] 2017-05-05 15:20
Duplicate of https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/162 . This was due to a change in DiffEqBase.jl to make the norms compatible with heterogeneous arrays of units, but this added a bug with complex numbers. The fix was easy, but I didn't realize this was used so much so I didn't put a release out! I'll make a hotfix tag right now.

**Comment by ChrisRackauckas** [comment] 2017-05-05 15:22
You can check out DiffEqBase.jl's master if you need the fix right now, and the hotfix tag PR is:

https://github.com/JuliaLang/METADATA.jl/pull/9158

It should go through quickly given it's a one commit tag.

**Closed by ChrisRackauckas** 2017-05-05 15:22 UTC

**Comment by jebej** [comment] 2017-05-05 15:26
Thanks Chris.
