### ISSUE TITLE
time-dependent Rosenbrock errors with autodifferentiation

### ISSUE THREAD

**Issue by sdwfrost** [JuliaDiffEq/OrdinaryDiffEq.jl#43] opened 2017-04-20 21:00 UTC
How do I access the time variable when specifying an ODE with time-varying rates. Here is a simple example:

```julia
using DiffEqBase
using OrdinaryDiffEq

function myode(t,u,du)
    du[1] = -t
end

u0 = [0.0]
tspan = (0.0,1.0)
prob = ODEProblem(myode,u0,tspan)
sol = solve(prob,Rosenbrock23())
```

The above gives:

```bash
MethodError: Cannot `convert` an object of type ForwardDiff.Dual{1,Float64} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.

in myode(::ForwardDiff.Dual{1,Float64}, ::Array{Float64,1}, ::Array{Float64,1}) ...
```

**Comment by ChrisRackauckas** [comment] 2017-04-21 02:02
Looks like the issue is how the wrapper works. This would make it easier.

https://github.com/JuliaDiff/ForwardDiff.jl/issues/218

Maybe I can find a workaround though.

**Comment by ChrisRackauckas** [comment] 2017-04-21 02:42
Fixed on master. Added a test to catch this in the future, and also threw in a correctness check for every algorithm while I was at it.

**Closed by ChrisRackauckas** 2017-04-21 02:42 UTC

**Comment by sdwfrost** [comment] 2017-04-21 05:08
Thanks! Is there any way I can use master right now, as the TravisCI build is broken?

**Comment by ChrisRackauckas** [comment] 2017-04-21 05:10
Not easily. There are some large changes since this is the last push of DiffEq 2.0 changes to lock in the interface. My tag list is:

```
DiffEqBase
OrdinaryDiffEq
StochasticDiffEq
RecursiveArrayTools
Sundials
ODE
ODEInterfaceDiffEq
LSODA
DimensionalPlotRecipes
DiffEqMonteCarlo
DiffEqParamEstim
SteadyStateDiffEq
DiffEqNoiseProcess
```

I believe 

```
DiffEqBase
OrdinaryDiffEq
DiffEqNoiseProcess
```

master will work without the others? I'm not sure. If you can't wait, go for. If you can wait, it's probably much easier.

**Comment by sdwfrost** [comment] 2017-04-21 05:14
Thanks! Any ETA on when all the packages will be aligned? I saw that you're caught up in advancement (good luck BTW).

**Comment by ChrisRackauckas** [comment] 2017-04-21 05:22
The last issue is @gabrielgellner 's https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/152 update. He said he'd get to it Friday, so I hope to have everything done by the weekend. That's the last API-related issue, and everything else is specific-package feature requests / new algorithms, so I think it's a good time to call it DiffEq 2.0. The only thing which may pause it is this:

https://discourse.julialang.org/t/differentialequations-pkg-wont-be-added/3194/39?u=chrisrackauckas

**Comment by sdwfrost** [comment] 2017-04-21 07:42
Thanks - I think I can wait! The masters of DiffEqBase and OrdinaryDiffEq throw the following error, as in the Travis builds. I can make the change locally to work with Rosenbrock23().

```
ERROR: LoadError: LoadError: UndefVarError: ArrayPartition not defined
```

**Comment by ChrisRackauckas** [comment] 2017-04-21 07:44
Yes, that's in RecursiveArrayTools. I noted that I think you'd need master on at least 4 packages.
