### ISSUE TITLE
v4.18.1 introduces major regression for out-of-place SVector integration

### ISSUE THREAD

**Issue by dkarrasch** [JuliaDiffEq/OrdinaryDiffEq.jl#571] opened 2018-12-06 10:54 UTC
As pointed out by @aharoun in the gitter channel, the following MWE shows a major regression:
```
using OrdinaryDiffEq, BenchmarkTools, StaticArrays

# inplace
function lorenz!(du,u,p,t)
    du[1] = 10.0*(u[2]-u[1])
    du[2] = u[1]*(28.0-u[3]) - u[2]
    du[3] = u[1]*u[2] - (8/3)*u[3]
end

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob! = ODEProblem(lorenz!,u0,tspan)
@btime solve($prob!,$(Tsit5())); # 876.144 μs (12961 allocations: 1.37 MiB)

# static
function lorenz_static(u,p,t)
    dx = 10.0*(u[2]-u[1])
    dy = u[1]*(28.0-u[3]) - u[2]
    dz = u[1]*u[2] - (8/3)*u[3]
    SVector{3}(dx,dy,dz)
end

u0 = @SVector [1.0,0.0,0.0]
tspan = (0.0,100.0)
probs = ODEProblem(lorenz_static,u0,tspan)
@btime solve($probs,$(Tsit5())); #  3.143 ms (59909 allocations: 4.05 MiB)
```
It persists under different choices for the solver. v4.18.0 still seems to be fine. Oddly, in Julia nightly (mine is 9 days old), the static computation is faster than the in-place integration, but still slower than in Julia v1.0.2. For comparsion, with OrdinaryDiffEq v4.18.0 the static calculation takes `455.696 μs (2319 allocations: 427.13 KiB)`.

**Comment by natschil** [comment] 2018-12-06 13:57
Given that the static version has more allocations than the non-static version, something else must also be broken.

**Comment by aharoun** [comment] 2018-12-06 14:02
In place version of MWE creates exactly the same output with v4.18.0 and v4.18.1. However the static array version gives slightly different results, specifically it uses more time nodes for the solution under v4.18.1. It looks like residual calculations somehow changed for static arrays as @devmotion mentioned.

**Comment by devmotion** [comment] 2018-12-06 14:48
I compared the out-of-place implementation for computing residuals for both `Array` and `SArray` on my computer:
```julia
using OrdinaryDiffEq, BenchmarkTools, StaticArrays

α, ρ = 1e-6, 1e-6

ũ, u₀, u₁ = rand(3), rand(3), rand(3)
@btime OrdinaryDiffEq.calculate_residuals($ũ, $u₀, $u₁, $α, $ρ, $DiffEqBase.ODE) # 65.563 ns (3 allocations: 144 bytes)

ũ, u₀, u₁ = rand(SVector{3}), rand(SVector{3}), rand(SVector{3})
@btime OrdinaryDiffEq.calculate_residuals($ũ, $u₀, $u₁, $α, $ρ, $DiffEqBase.ODE_DEFAULT_NORM) # 2.822 μs (59 allocations: 3.56 KiB)
```
Clearly the version with static arrays is much slower and produces more allocations. However, since `Array` and `SArray` dispatch to different methods and hence use different implementations, I performed the following fair comparison as well:
```julia
using OrdinaryDiffEq, BenchmarkTools, StaticArrays

f(ũ, u₀, u₁) = @. ũ / (1e-6 + max(abs(u₀), abs(u₁)) * 1e-6)

ũ, u₀, u₁ = rand(3), rand(3), rand(3)
@btime f($ũ, $u₀, $u₁) # 40.473 ns (1 allocation: 112 bytes)

ũ, u₀, u₁ = rand(SVector{3}), rand(SVector{3}), rand(SVector{3})
@btime f($ũ, $u₀, $u₁) # 2.061 μs (44 allocations: 3.59 KiB)
```
So it seems, broadcasting static arrays is amazingly slow and causes many allocations.

**Comment by dkarrasch** [comment] 2018-12-06 14:51
Ok, it seems that it's the time it takes to compute the residual, not so much the values. In the fast setting (v.4.18.0 and Julia v1.0.2) there are 1116 time steps taken, in the slow setting (4.18.1 and Julia v1.0.2) it is 1267 time steps. (I was typing while @devmotion posted his comment)

@devmotion Does it change anything if you write the `.`s manually?

**Comment by aharoun** [comment] 2018-12-06 14:58
It looks like this is a v4.18.1 + Julia 1.0.2 issue. Because  v4.18.0 and v4.18.1 give similar timing for static array version with Julia 1.1.

**Comment by ChrisRackauckas** [comment] 2018-12-06 14:59
@andyferris do you know about this performance regression when broadcasting StaticArrays but is fixed in v1.1?

We may want to just create workaround dispatches for the residual calculation then. Not broadcasting the norms in there wasn't correct.

**Comment by dkarrasch** [comment] 2018-12-06 15:01
Hold on, I just tried myself. Try this
```
using OrdinaryDiffEq, BenchmarkTools, StaticArrays

f(ũ, u₀, u₁) = ũ ./ (1e-6 .+ max.(abs.(u₀), abs.(u₁)) * 1e-6)

ũ, u₀, u₁ = rand(3), rand(3), rand(3)
@btime f($ũ, $u₀, $u₁) # 40.473 ns (1 allocation: 112 bytes)

ũ, u₀, u₁ = rand(SVector{3}), rand(SVector{3}), rand(SVector{3})
@btime f($ũ, $u₀, $u₁) # 2.061 μs (44 allocations: 3.59 KiB)
```
I hope I haven't messed up the dots, but this broadcasting is superfast on StaticVectors.

**Comment by devmotion** [comment] 2018-12-06 15:05
I can reproduce your results but you forgot to dot the multiplication, it seems. With that missing dot static arrays are still slow in my benchmarks.

**Comment by dkarrasch** [comment] 2018-12-06 15:09
I can confirm your comment on the speed, but the multiplication does not occur in the referenced commit, and it is also unnecessary. It's multiplication of a (static) vector by a scalar, that doesn't require broadcast. Still, it points to some issue, I guess.

**Comment by devmotion** [comment] 2018-12-06 15:13
>  multiplication does not occur in the referenced commit, and it is also unnecessary

It is required, one should be able to specify relative and absolute tolerances element-wise: http://docs.juliadiffeq.org/latest/basics/common_solver_opts.html#Stepsize-Control-1

**Comment by devmotion** [comment] 2018-12-08 13:58
If we want to add that workaround we should just dispatch on `SArray`, so it should not affect any other use cases.

**Comment by YingboMa** [comment] 2018-12-08 17:00
It might be because of that in Julia 1.0, Julia will not elide bounds check with `@inline`, but only when the callee is annotated with `Base.@propagate_inbounds`. I will look into this.

**Closed** 2018-12-09 19:50 UTC
