### ISSUE TITLE
cell growth example not updating number of cells, i.e. resize! not working as intended, 

### ISSUE THREAD

**Issue by zahachtah** [JuliaDiffEq/OrdinaryDiffEq.jl#702] opened 2019-03-18 15:08 UTC
looks to be an issue specific to the automatic switching methods according to Chris.

reproduce using this code:

```julia
using OrdinaryDiffEq
const α = 0.3
function f(du,u,p,t)
  for i in 1:length(u)
    du[i] = α*u[i]
  end
end
function condition(u,t,integrator) # Event when event_f(u,t) == 0
  1-maximum(u)
end
function affect!(integrator)
  u = integrator.u
  resize!(integrator,length(u)+1)
  maxidx = findmax(u)[2]
  Θ = rand()
  u[maxidx] = Θ
  u[end] = 1-Θ
  nothing
end
callback = ContinuousCallback(condition,affect!)
u0 = [0.2]
tspan = (0.0,100.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),callback=callback)
map((x)->length(x),sol[:])
sol = solve(prob,AutoTsit5(Rosenbrock23()),callback=callback)
map((x)->length(x),sol[:])
```

expected output of last line should be Int array with increasing values but it gives array of ones.

**Comment by zahachtah** [comment] 2019-03-22 14:07
Is there a workaround for this in the meantime? My phytoplankton model is ready to go :-)

**Comment by ChrisRackauckas** [comment] 2019-03-22 15:03
Does it need to use the autoswitch algorithm?

**Comment by zahachtah** [comment] 2019-03-22 15:24
Oh, I misunderstood autoswitch.....

No, of course not, turning that of makes it work just fine. sorry

**Comment by zahachtah** [comment] 2019-03-23 09:46
So I had this problem in my code that it seemed that any new cell had very strange behaviour. In the end I went back to the original example (posted above) and I checked the solution (divisions seem to work now). ploting the end solution one sees the problem:

```
julia> sol.u[end]
142-element Array{Float64,1}:
 1.1025765081680845e10
 1.6013944732846132e10
 2.2468173590938503e10
 1.7182740622399776e10
 2.347462219020223e10 
 2.454796026651964e9  
 8.168841932182818e9  
 1.5996956094909502e10
 2.697987506407831e10 
 2.3678391244781097e10
 7.716450687810062e9  
 8.774639231897194e9  
 1.1717070401710297e10
 2.210621996840792e10 
 2.9234269854881104e10
 1.484689894405136e10 
 2.2845153791509676e9 
 ⋮                    
 1.6968125500270754e10
 1.5728149839138386e10
 2.171839977082052e10 
 5.3326532230684185e9 
 1.3857392269280869e10
 1.966396918650231e10 
 8.478436432917869e9  
 1.1070672385546865e10
 1.1341922438370492e8 
 2.250069654471181e10 
 1.9393417994653297e10
 1.7937561896299245e9 
 1.6297743219281202e10
 2.575398089829292e9  
 2.9043714359249886e10
 1.6687643451566027e10
```
apparently whatever is done to u in the affect! function does not seem to get applied which is what I saw in my code too. 

Any idea what this could be????

**Comment by ChrisRackauckas** [comment] 2019-03-26 05:10
I'll take a look at this when I am back from my trip. Ping me next Monday.

**Comment by zahachtah** [comment] 2019-04-04 12:33
@ChrisRackauckas ping :-)

**Comment by ChrisRackauckas** [comment] 2019-05-26 02:14
I realized that you made the model insane. If you want it to catch all of the events, you can make the effect check for multiple crossings:

```julia
using OrdinaryDiffEq
const α = 0.3
function f(du,u,p,t)
  for i in 1:length(u)
    du[i] = α*u[i]
  end
end
function condition(u,t,integrator) # Event when event_f(u,t) == 0
  1-maximum(u)
end
function affect!(integrator)
  u = integrator.u
  idxs = findall(x->x>1-1000eps(),u)
  old_length = length(u)
  resize!(integrator,old_length+length(idxs))
  for (i,j) in enumerate(idxs)
    Θ = rand()
    u[j] = Θ
    u[old_length+i] = 1-Θ
  end
  nothing
end
callback = ContinuousCallback(condition,affect!)
u0 = [0.2]
tspan = (0.0,49.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),callback=callback)
```

However, you need exponential amounts of memory because the event happens more and more often, so... I'm not sure what you're trying to do with this generalization but it's not going to be efficient.

**Comment by ghyatzo** [comment] 2019-11-07 01:27
Any news regarding the resize! function? Tried to run the code from the example again but to no avail. The affect function is called but no change to the u array.
(Also addat! doesn't seem to work)

copy-pasted the code from the wiki page.

**Comment by ChrisRackauckas** [comment] 2019-11-07 04:02
Interesting I'll double check that tonight. It's part of the standard tests though

**Comment by ghyatzo** [comment] 2019-11-07 20:55
Wonderful, thanks for your time.
In the mean time i try to give all the info i can.
I played around with Juno debugger, (couldn't really dig deep since i started using Julia and this library only 2 days ago).
Here's what i found so far:

 - `resolve!(integrator, lentgh(u)+1)` correctly calls `resize!(integrator::ODEIntegrator, i::Int)`.
 - inside `resize!(integrator::ODEIntegrator, i::Int)` the for loop
    `for c in full_cache(cache)
        resize!(c,i)
    end`
is skipped after an `iterate(())` it evaluates a `===(nothing, nothing)`, `intrinsicFunction(true)` and jumps outside.

- `resize_non_user_cache` returns `nothing`

After all this `u` is unchanged.
Sadly i got a bit lost, both because i couldn't find the correct dispatch of full_cache (or most probably i didn't understood what what i found was doing), but maybe the problem is that the `resize!(c,i)` is not being run (`full_cache(cache)` somehow failing?)

I'm tried to look for the implementation of `resize!(c,i)` but amidst all the different kind of different dispatch types i couldn't find the right one.

Hope this information is helpful and not more confusing.
Cheers!

**Comment by ChrisRackauckas** [comment] 2019-11-11 05:21
I just double checked it.

```julia
using OrdinaryDiffEq
const α = 0.3
function f(du,u,p,t)
  for i in 1:length(u)
    du[i] = α*u[i]/length(u)
  end
end
function condition(u,t,integrator) # Event when event_f(u,t) == 0
  1-maximum(u)
end
function affect!(integrator)
  u = integrator.u
  resize!(integrator,length(u)+1)
  maxidx = findmax(u)[2]
  Θ = rand()
  u[maxidx] = Θ
  u[end] = 1-Θ
  nothing
end
callback = ContinuousCallback(condition,affect!)
u0 = [0.2]
tspan = (0.0,49.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),callback=callback)

using Plots
plot(sol.t,map((x)->length(x),sol[:]),lw=3,
     ylabel="Number of Cells",xlabel="Time")
```

as expected, this test is run daily and the plot still works, so I think it's fine to close this. @ghyatzo come up with a reproducible example on Julia 1.2 in a new issue if you want to follow up on this, since I cannot follow your notes because the example in this issue works.

**Closed by ChrisRackauckas** 2019-11-11 05:21 UTC
